Backported some improvements from wioe5_ham1_mysql
git-svn-id: svn+ssh://subversion.munts.net/src/trunk/muntsos@23396 06ee2f96-5407-11de-8bab-f3d7589a4122

diff --git a/extensions/wioe5_ham1_rabbitmq/S00wioe5_ham1_rabbitmq b/extensions/wioe5_ham1_rabbitmq/S00wioe5_ham1_rabbitmq
--- a/extensions/wioe5_ham1_rabbitmq/S00wioe5_ham1_rabbitmq
+++ b/extensions/wioe5_ham1_rabbitmq/S00wioe5_ham1_rabbitmq
@@ -1,5 +1,12 @@
 #! /bin/sh
 
+# Check for libwioe5ham1.so
+
+if [ ! -f /usr/local/lib/libwioe5ham1.so ]; then
+  echo "ERROR: You must install the libwioe5ham1 extension package."
+  exit 1
+fi
+
 # Run wioe5_ham1_rabbitmq as a background process
 
 detach /usr/local/bin/wioe5_ham1_rabbitmq
